myOrderManagement/force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Order_cs</relationshipName>
    <type>Lookup</type>
</CustomField>

myOrderManagement/force-app/main/default/classes/OrderService.cls
public with sharing class OrderService {

	@AuraEnabled
	public static Order__c createOrder(Id accountId, List<OrderItem__c> orderItems) {
		if (accountId == null || orderItems.isEmpty()) {
			throw new AuraHandledException('Account and Order Items are required.');
		}

		Order__c newOrder = new Order__c(Account__c = accountId);

		insert newOrder;

		for (OrderItem__c item : orderItems) {
			item.Order__c = newOrder.Id;
		}
		insert orderItems;

		return newOrder;
	}
}