myOrderManagement/force-app/main/default/objects/Product__c/fields/FamilyVal__c.field-meta.xml
<CustomField>
    <fullName>FamilyVal__c</fullName>
    <label>FamilyVal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>something</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

myOrderManagement/force-app/main/default/objects/Product__c/fields/TypeVal__c.field-meta.xml
<CustomField>
    <fullName>TypeVal__c</fullName>
    <label>TypeVal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1</fullName>
            </value>
            <value>
                <fullName>something</fullName>
            </value>
            <value>
                <fullName>Type 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

myOrderManagement/force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {
	@AuraEnabled(cacheable=true)
	public static Product__c getProductDetails(Id productId) {
		if (String.isEmpty(productId)) {
			throw new AuraHandledException(' Invalid Product ID');
		}

		try {
			return [
					SELECT Id, Name, Description__c, TypeVal__c, FamilyVal__c, Price__c, Image__c
					FROM Product__c
					WHERE Id = :productId
					LIMIT 1
			];
		} catch (Exception e) {
			throw new AuraHandledException('Error fetching product details: ' + e.getMessage());
		}
	}

	@AuraEnabled
	public static void createProduct(Product__c productData) {
		try {
			Product__c newProduct = new Product__c(
					Name = productData.Name,
					Description__c = productData.Description__c,
					TypeVal__c = productData.TypeVal__c,
					FamilyVal__c = productData.FamilyVal__c,
					Price__c = productData.Price__c
			);

			insert newProduct;

		} catch (Exception e) {
			throw new AuraHandledException('Error creating product: ' + e.getMessage());
		}
	}


}